# Generated by Django 5.2.1 on 2025-05-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_user_is_confirmed_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(default="avatars/default.png"),
        ),
    ]
